# Generated by Django 5.0.4 on 2024-05-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_rate_interestrate_intrestrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestRate',
        ),
        migrations.DeleteModel(
            name='LoanApproval',
        ),
    ]
