# Generated by Django 5.0.4 on 2024-05-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_budget_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
    ]
