# Generated by Django 5.0.4 on 2024-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
