# Generated by Django 5.0.4 on 2024-05-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_blacklistedaccesstoken_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklistedaccesstoken',
            old_name='user',
            new_name='user_id',
        ),
    ]
